# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611dc525aababb0fee6c614ae217c32fbf42f83fbebbf44485db04fa70ac2e73db4aa6b07d6d26816ae96c59494286555c4d0f086a423616366987ee5c24f6af

test:
  secret_key_base: aefddc3249bdeda504898c906a5155591889591fae0c442e58f518f179f1e56e6c0edaf1420a9f21942a2450478f487ddcb3745e976a158156b3c7a17f4da950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
